### ISSUE TITLE
Preview?

### ISSUE THREAD

**Issue by xitude** [mmcc/videojs-skin-twitchy#1]
Fancy posting a preview of what to expect, Im quite interested in this.

**Comment by SoraKohaku** [comment]
hmmm I think same as demo. in html5 already easy used. I kind interesting too. because its easy for my web engine :+1:

**Comment by mmcc** [comment]
Hey sorry about that, I didn't see this one come through. There's a preview on GH Pages: http://blog.htbx.net/videojs-skin-twitchy/.
